import type { CuratedPlace } from "./types";

// ⚠️ 아래는 전부 샘플(더미) 데이터입니다. 실제 추천 품질을 위해 본인이
// 경험한 장소 정보로 교체해야 합니다. "(샘플 데이터 - 교체 필요)" 마커가
// 있는 필드는 모두 본인 데이터로 덮어쓰세요.
export const CURATED_PLACES: CuratedPlace[] = [
  {
    id: "sample-cafe-1",
    name: "샘플 카페 1",
    region: "서울",
    subRegion: "성수",
    category: "카페",
    moodTags: ["분위기", "사진", "조용함"],
    myRating: 4.5,
    parkingInfo: "(샘플 데이터 - 교체 필요)",
    myNote: "(샘플 데이터 - 교체 필요)",
    companionFit: ["연인", "친구"],
    naverUrl: "https://map.naver.com/p/sample-1",
  },
  {
    id: "sample-cafe-2",
    name: "샘플 카페 2",
    region: "서울",
    subRegion: "연남",
    category: "카페",
    moodTags: ["커피", "로스터리"],
    myRating: 4.0,
    parkingInfo: "(샘플 데이터 - 교체 필요)",
    myNote: "(샘플 데이터 - 교체 필요)",
    companionFit: ["혼자", "친구"],
    naverUrl: "https://map.naver.com/p/sample-2",
  },
  {
    id: "sample-restaurant-1",
    name: "샘플 맛집 1",
    region: "서울",
    subRegion: "한남",
    category: "맛집",
    moodTags: ["분위기", "데이트"],
    myRating: 4.0,
    parkingInfo: "(샘플 데이터 - 교체 필요)",
    myNote: "(샘플 데이터 - 교체 필요)",
    companionFit: ["연인", "친구", "가족"],
    naverUrl: "https://map.naver.com/p/sample-3",
  },
  {
    id: "sample-nature-1",
    name: "샘플 자연 1",
    region: "서울",
    subRegion: "종로",
    category: "자연",
    moodTags: ["자연", "산책", "조용함"],
    myRating: 4.0,
    parkingInfo: "(샘플 데이터 - 교체 필요)",
    myNote: "(샘플 데이터 - 교체 필요)",
    companionFit: ["혼자", "가족", "부모님"],
    naverUrl: "https://map.naver.com/p/sample-4",
  },
  {
    id: "sample-exhibition-1",
    name: "샘플 전시 1",
    region: "서울",
    subRegion: "용산",
    category: "전시",
    moodTags: ["전시", "사진", "실내"],
    myRating: 3.5,
    parkingInfo: "(샘플 데이터 - 교체 필요)",
    myNote: "(샘플 데이터 - 교체 필요)",
    companionFit: ["연인", "친구"],
    naverUrl: "https://map.naver.com/p/sample-5",
  },
];
